---

- ansible.builtin.debug:
    var: kvm_deployment

- name: Append kvm_deployment.virtual_machines in target_vms_list
  ansible.builtin.set_fact:
    target_vms_list: "{{target_vms_list + [item.name]}}"
  with_items: "{{kvm_deployment.virtual_machines}}"

- ansible.builtin.debug:
    msg:
      - "Selected Guest Template: {{kvm_deployment.template}}"
      - "Ansible will create following clones from above template:"
      - "{{target_vms_list}}"

- ansible.builtin.pause:
    echo: yes
    minutes: 15
    prompt: "\nINFO: You are processing operation on above input:\n-> Review and continue"

- block:
  - ansible.builtin.debug:
      msg:
        - "You have forced cloning"
        - "Existing VM will be deleted"

  - name: Remove VM if exists
    ansible.builtin.shell: |
        if virsh list --all |egrep {{item}};then
          if virsh domstate {{item}}|egrep "shut off";then
            virsh shutdown {{item}}
            sleep 10
          fi
          virsh undefine {{item}} --remove-all-storage
        fi
        exit 0
    with_items: "{{target_vms_list}}"
  when: force_clone|bool

# _guests.list_vms will store all kvm virtual machines after running this task.
- name: List all VMs
  community.libvirt.virt:
    command: list_vms
  register: _guests

- name: Check guest_exists=false if guest not available
  ansible.builtin.debug:
    msg: "Cloning will be skipped for {{item.name}}. It already exists"
  with_items: "{{kvm_deployment.virtual_machines}}"
  when: item.name in _guests.list_vms

- name: Include virt-clone.yml
  ansible.builtin.include_tasks: virt-clone.yml
  with_items: "{{kvm_deployment.virtual_machines}}"
  loop_control:
    loop_var: guest
  when: guest.name not in _guests.list_vms