
- ansible.builtin.debug:
    msg: "Creating clone {{guest.name}} from {{kvm_deployment.template}}"

- name: create-vm-clones | Create clone
  ansible.builtin.shell: |
    virt-clone -o {{kvm_deployment.template}} -n {{guest.name}} \
      -f /var/lib/libvirt/images/{{guest.name}}.qcow2

- name: create-vm-clones | Get dominfo of created VM
  ansible.builtin.command: virsh dominfo {{guest.name}}
  register: _dominfo

- ansible.builtin.debug:
    var: _dominfo.stdout_lines

- name: create-vm-clones | Get domblklist of created VM
  ansible.builtin.command: virsh domblklist {{guest.name}}
  register: _domblk

- ansible.builtin.debug:
    var: _domblk.stdout_lines

