---

- ansible.builtin.setup:

- ansible.builtin.debug:
    var: ansible_cmdline

- name: disable-ipv6 | Set fact disable_ipv6
  set_fact:
      disable_ipv6: true
  when: ansible_cmdline["ipv6.disable"] is not defined or ansible_cmdline["ipv6.disable"] != "1"

- block:
  - name: disable-ipv6 | Get current GRUB_CMDLINE_LINUX settings for RedHat machines
    shell: cat /etc/default/grub|egrep ^GRUB_CMDLINE_LINUX|cut -d'"' -f2
    register: _current_grub_cmd
    when: ansible_os_family == "RedHat"

  - name: disable-ipv6 | Get current GRUB_CMDLINE_LINUX_DEFAULT settings for Debian machine
    shell: cat /etc/default/grub|egrep ^GRUB_CMDLINE_LINUX_DEFAULT|cut -d'"' -f2
    register: _current_grub_cmd
    when: ansible_os_family == "Debian"

  - debug:
      var: _current_grub_cmd.stdout

  - name: disable-ipv6 | Set fact to disable ipv6
    set_fact:
      _new_kernel_param: "{{_current_grub_cmd.stdout + ' ipv6.disable=1'}}"
    when: _current_grub_cmd.stdout != ""

  - name: disable-ipv6 | Set fact to disable ipv6
    set_fact:
      _new_kernel_param: "ipv6.disable=1"
    when: _current_grub_cmd.stdout == ""

  - debug:
      var: _new_kernel_param

  - name: disable-ipv6 | Take backup of /etc/default/grub
    copy:
      src: /etc/default/grub
      dest: /etc/default/grub-{{ansible_date_time.iso8601_basic_short}}
      mode: 0644
      owner: root
      group: root
      remote_src: yes

  - name: disable-ipv6 | Update /etc/default/grub with new kernel param for RedHat machines
    lineinfile:
      path: /etc/default/grub
      regexp: '^GRUB_CMDLINE_LINUX='
      line: 'GRUB_CMDLINE_LINUX="{{_new_kernel_param}}"'
    when: ansible_os_family == "RedHat"

  - name: disable-ipv6 | Update /etc/default/grub with new kernel param for Debian machines
    lineinfile:
      path: /etc/default/grub
      regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
      line: 'GRUB_CMDLINE_LINUX_DEFAULT="{{_new_kernel_param}}"'
    when: ansible_os_family == "Debian"

  - name: disable-ipv6 | Generate grub config for ubuntu machines
    command: grub-mkconfig -o /boot/grub/grub.cfg
    when: ansible_os_family == "Debian"

  - name: disable-ipv6 | Generate grub config for RedHat based machines
    command: grub2-mkconfig -o /boot/grub2/grub.cfg
    when: ansible_os_family == "RedHat"

  # Machine must be rebooted outside this role
  #- name: Reboot host
  #  reboot:
  #    reboot_timeout: 600
  #    test_command: "uptime"

  - name: set fact host_reboot=true
    ansible.builtin.set_fact:
      host_reboot: true
  when: disable_ipv6| default('false')|bool
