---
# Create KVM Guest Template
- hosts: localhost
  gather_facts: true
  become: yes
  
  vars:
    guest_os: ubuntu2204
   
  tasks:
  - include_role: 
      name: kvm-guest-template
      tasks_from: create-guest-template-using-cloud-image.yml

- hosts: new_kvm_guest
  gather_facts: true
  become: true

  vars:
    guest_os: ubuntu2204
    host_reboot: false
    template_default_vars: "{{lookup('env','PWD')}}/kvm-guest-template/defaults/main.yml"
  
  pre_tasks:
  - name: Include vars from file provided in custom_guest_input extra var
    ansible.builtin.include_vars:
      file: "{{custom_guest_input}}"
    when: custom_guest_input is defined

  - name: Include default vars from kvm-guest-template
    ansible.builtin.include_vars:
      file: "{{template_default_vars}}"
    when: custom_guest_input is not defined

  tasks:    
  - name: Include os-tuning role to setup vconsole, disable ipv6 and disable biosdevname
    ansible.builtin.include_role:
      name: os-tuning
      tasks_from: main.yml

  - name: Reboot host 
    ansible.builtin.shell: |
      virsh shutdown {{image_type[guest_os]['template']['name']}}
      [ $? != 0 ] && echo "Failed to shutdown VM" && exit 1
      sleep 10
      virsh start {{image_type[guest_os]['template']['name']}}
      sleep 30
    args:
      executable: /bin/bash
    delegate_to: localhost
    when: host_reboot|bool

  - name: Update ansible facts
    ansible.builtin.setup:

  - name: Include os-tuning role to set dhcp identifier
    ansible.builtin.include_role:
      name: os-tuning
      tasks_from: dhcp-identifier.yml

  - name: Shutdown {{image_type[guest_os]['template']['name']}} 
    ansible.builtin.shell: |
      virsh shutdown {{image_type[guest_os]['template']['name']}}
      [ $? != 0 ] && echo "Failed to shutdown VM" && exit 1
      sleep 10
    delegate_to: localhost 