---

- ansible.builtin.debug:
    var: kvm_deployment
  run_once: true

- ansible.builtin.pause:
    echo: yes
    minutes: 15
    prompt: "\nINFO: You are processing operation on above input:\n-> Review and continue"

- name: setup-static-ip | Run Asserts
  ansible.builtin.assert:
    that:
      - kvm_deployment.virtual_machines is defined

- name: setup-static-ip | Bring up interfaces
  ansible.builtin.shell: |
    for e in $(ip -o link show | awk -F': ' '{print $2}'|egrep -v lo);do
      ip link set $e up
    done

- name: setup-static-ip | Include vars from {{machines_mapping}}
  ansible.builtin.include_vars: "{{machines_mapping}}"

# vms_name_ip_mapping is coming from machines_mapping file
- name: setup-static-ip | Include tasks from static.yml
  ansible.builtin.include_tasks: static.yml
  with_items: "{{vms_name_ip_mapping}}"
  loop_control:
    loop_var: machine

- name: Review Generated Inventory
  ansible.builtin.debug:
    msg: "{{machines_mapping}} machines inventory is retained for further usages"
  delegate_to: localhost
  run_once: true