---

- ansible.builtin.debug:
    var: kvm_deployment

- ansible.builtin.pause:
    echo: yes
    minutes: 15
    prompt: "\nINFO: You are processing operation on above input:\n-> Review and continue"

- name: setup-static-ip | Run Asserts
  ansible.builtin.assert:
    that:
      - kvm_deployment.virtual_machines is defined

- name: setup-static-ip | Template out netplan config
  ansible.builtin.template:
    src: "/var/tmp/{{inventory_hostname}}-netplan.yaml"
    dest: /etc/netplan/50-cloud-init.yaml
    mode: 0644
    owner: root
    group: root
  register: _static_config

- name: setup-static-ip | Enable network changes
  command: netplan apply
  when: _static_config is changed
