---

- setup:

- name: Set fact disable_ipv6
  set_fact:
      disable_ipv6: true
  when: ansible_cmdline["ipv6.disable"] is not defined or ansible_cmdline["ipv6.disable"] != "1"

- name: Check 'ipv6.disable=1' param in /etc/default/grub
  shell: cat /etc/default/grub|egrep ^GRUB_CMDLINE_LINUX|egrep "ipv6.disable=1"
  register: _check_disable_ipv6
  ignore_errors: true

- block:
  - name: Get current GRUB_CMDLINE_LINUX settings for RedHat machines
    shell: cat /etc/default/grub|egrep ^GRUB_CMDLINE_LINUX|cut -d'"' -f2
    register: _current_grub_cmd
    when: ansible_os_family == "RedHat"

  - name: Get current GRUB_CMDLINE_LINUX_DEFAULT settings for Debian machine
    shell: cat /etc/default/grub|egrep ^GRUB_CMDLINE_LINUX_DEFAULT|cut -d'"' -f2
    register: _current_grub_cmd
    when: ansible_os_family == "Debian"

  - debug:
      var: _current_grub_cmd.stdout

  - name: Set fact to disable ipv6
    set_fact:
      _new_kernel_param: "{{_current_grub_cmd.stdout + ' ipv6.disable=1'}}"
    when: _current_grub_cmd.stdout != ""

  - name: Set fact to disable ipv6
    set_fact:
      _new_kernel_param: "ipv6.disable=1"
    when: _current_grub_cmd.stdout == ""

  - debug:
      var: _new_kernel_param

  - name: Take backup of /etc/default/grub
    copy:
      src: /etc/default/grub
      dest: /etc/default/grub-{{ansible_date_time.iso8601_basic_short}}
      mode: 0644
      owner: root
      group: root
      remote_src: yes

  - name: Update /etc/default/grub with new kernel param for RedHat machines
    lineinfile:
      path: /etc/default/grub
      regexp: '^GRUB_CMDLINE_LINUX='
      line: 'GRUB_CMDLINE_LINUX="{{_new_kernel_param}}"'
    when: ansible_os_family == "RedHat"

  - name: Update /etc/default/grub with new kernel param for Debian machines
    lineinfile:
      path: /etc/default/grub
      regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
      line: 'GRUB_CMDLINE_LINUX_DEFAULT="{{_new_kernel_param}}"'
    when: ansible_os_family == "Debian"

  - name: Generate grub config for ubuntu machines
    command: grub-mkconfig -o /boot/grub/grub.cfg
    when: ansible_os_family == "Debian"

  - name: Generate grub config for RedHat based machines
    command: grub2-mkconfig -o /boot/grub2/grub.cfg
    when: ansible_os_family == "RedHat"

  - name: Reboot host
    reboot:
      reboot_timeout: 600
      test_command: "uptime"

  - setup:
  when: disable_ipv6| default('false')|bool
